# project
project.name=task-tracker
project.group=org.esc
project.version=1.0.0
main.class=org.esc.tasktracker.EscTaskTrackerApplication

# layout
root.dir=.
src.main.dir=src/main/kotlin
src.test.dir=src/test/kotlin
resources.dir=src/main/resources
build.dir=build
build.classes.dir=build/classes
build.resources.dir=build/resources
build.lib.dir=build/lib
dist.dir=build/libs

# kotlin
kotlin.home=/opt/homebrew/Cellar/kotlin/2.1.20/libexec
kotlin.lib=${kotlin.home}/lib
kotlin.ant.jar=${kotlin.lib}/kotlin-ant.jar

# ivy
ivy.jar.file=/opt/homebrew/Cellar/ivy/2.5.3/libexec/ivy-2.5.3.jar
ivy.jar.dir=/opt/homebrew/Cellar/ivy/2.5.3/libexec

# runtime config
spring.profile=local
external.config.dir=./config
dotenv.file=./.env